name: Compile MQL5 to EX5
on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile MQL5
        uses: fx31337/mql-compile-action@master
        with:
          init-platform: mt5
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file-path: "**/*.mq5"

      - name: Upload Compiled EX5
        uses: actions/upload-artifact@v4
        with:
          name: tedderman-ex5-indicator
          path: "**/*.ex5"
          
